## Playing with NumPy
Some snippets from Chapter 2 of "A Student's Guide to Python for Physical Modeling". A lot more focus is placed on NumPy as I have a much stronger grasp of native Python data types (list, tuples, strings, etc.). I also skinned past NumPy features that I was already very accustomed to.

In [1]:
import numpy as np

### 2.2 Lists, Tuples, and Arrays

#### 2.2.7 Slicing

##### Your Turn 2D

Explain the output you get from each line. Can you construct a slicing
operation that returns only the odd entries of a?

In [51]:
a = np.arange(20)
a[:]      # Returns all elements
a[::]     # Returns all elements
a[5:15]   # Returns a sliced array ranging from index 5 to index 14
a[5:15:3] # Returns a sliced array ranging from index 5 to index 14 in steps of 3
a[5::]    # Returns a sliced array starting at index 5
a[:5:]    # Returns a sliced array ending with index 4
a[::5]    # Returns a sliced array ranging start to end of array a in steps of 5

a[1::2]   # Returns only the odd elements of array a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 2.2.4 Concatentation of arrays

Looking at np.hstack (horizontal stack) and np.vstack (vertical stack).

In [13]:
a = np.zeros((2,3))
b = np.ones((2,3))
# It is important that a and b have the same number of rows
# for hstack and the same number of columns for vstack.
h = np.hstack([a,b]) # Concatenates arrays a and b horizontally
v = np.vstack([a,b]) # Concatenates arrays a and b vertically

print(h)
print(v)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 2.2.8 Flattening an array

Working with ravel and flatten respectively and exploring their differences.

In [3]:
a = np.array([[1,2],[2,1]])
b = a.flatten()
c = np.ravel(a)
d = a.ravel()

# Flatten creates a new separate array. 
# However, ravel creates an array that still references the original one.
b[1] = 11
c[2] = 22
print(a)
print(b)
print(c)
print(d)

[[ 1  2]
 [22  1]]
[ 1 11  2  1]
[ 1  2 22  1]
[ 1  2 22  1]


#### 2.2.9 Reshaping an array

Numpy array shape and reshape.

In [5]:
a = np.arange(12)
b = np.reshape(a, (3,4))
c = b.reshape((2,6))
d = c.reshape((2,3,2))

# Reshape requires that the requested shape be consistent 
# with the number of elements that the source array contains.
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


#### 2.2.10 Lists and arrays as indices

You can use a Boolean array for logical indexing - something that is very new to me!

In [12]:
a = np.arange(-10,11)
less_than_five = (abs(a) < 5) # Applies the abs() function to mutate the NumPy array 
                              # then applies < 5 to create a Boolean array
b = a[less_than_five]         # Logical indexing!

# Alternatively
b = a[abs(a) < 5]
print(b)

[-4 -3 -2 -1  0  1  2  3  4]


### 2.5 Array Operations

#### 2.5.1 Vectorizing Math

With vectorization, you apply an operation to an entire array instead of a scalar.

In [16]:
# Quadratic formula applied over array a
b, c = 2, -1
a = np.arange(-1,2,0.3)
(-b + np.sqrt(b**2-4*a*c))/(2*a) # Several instances of scalar multiplication of a vector

array([1.        , 0.64611063, 0.56350833, 0.51316702, 0.47722558,
       0.44948974, 0.42705098, 0.40830698, 0.39228096, 0.37833393])

##### Your Turn 2F (a)
a. We often wish to evaluate the function y = e^−(x^2) over a range of x
values. Figure out how to code this in vectorized notation.

In [24]:
x = np.arange(0,4,0.3) # An arbitrary array
y = np.exp(-1*(x**2))  # NumPy provides an exponential (e) function
y

array([1.00000000e+00, 9.13931185e-01, 6.97676326e-01, 4.44858066e-01,
       2.36927759e-01, 1.05399225e-01, 3.91638951e-02, 1.21551783e-02,
       3.15111160e-03, 6.82328053e-04, 1.23409804e-04, 1.86437423e-05,
       2.35257520e-06, 2.47959602e-07])

##### Your Turn 2F (b)
b. We often wish to evaluate the function e^(−µ)µ^n/(n!) over the integer values n = 0, 1,..., N. Here, the exclamation point denotes the factorial function. Figure out how to code this in vectorized notation for N = 10 and µ = 2. (You may want to import the factorial function from SciPy’s collection of special functions, scipy.special.)

In [18]:
from scipy.special import factorial

In [22]:
N, mu = 10, 2
n = np.arange(N+1)
(np.exp(-1*mu)*mu**n)/factorial(n)

array([1.35335283e-01, 2.70670566e-01, 2.70670566e-01, 1.80447044e-01,
       9.02235222e-02, 3.60894089e-02, 1.20298030e-02, 3.43708656e-03,
       8.59271640e-04, 1.90949253e-04, 3.81898506e-05])

Performing the dot product with NumPy.

In [27]:
a = np.array([1,2,3])
b = np.array([1,0.1,0.01])
a*b
np.dot(a, b) # The dot product is easy to perform here as a and b have the same length.

1.23

#### 2.5.2 Reducing an array

Array reduction occurs when an operation combines elements of an array resulting in a smaller array.

In [36]:
a = np.vstack((np.arange(20),np.arange(100,120))) # Concentate two arrays vertically
b = np.sum(a,0) # Sums columns of a
c = np.sum(a,1) # Sums rows of a
d = np.sum(a)   # Sums all of a

print("Concatenated array a")
print(a)
print("\nSum of array a over axis=0")
print(b)
print("\nSum of array a over axis=1")
print(c)
print("\nSum of array a")
print(d)

Concatenated array a
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]]

Sum of array a over axis=0
[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138]

Sum of array a over axis=1
[ 190 2190]

Sum of array a
2380


See if you can explain how the following code calculates 10!:

In [37]:
ten_factorial = np.arange(1,11).prod()
# np.arange(1,11) creates an array spanning from 1 to 10 in steps of 1.
# prod() then computes the product of all the elements in the array.
# (10*9*8*..*1) is equivalent to 10!

ten_factorial

3628800